# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# plugins
gems: [jekyll-paginate]

# Conversion
markdown:     kramdown
highlighter:  rouge
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

#站点基础配置
title: On the Desk
subTitle:  这一生与Desk的不解之缘
description: 前几天在组内的wiki上用markdown写了一些开发过程，感觉这么写东西的方式是非常舒服的。感谢Jhon Gruber的创造...
url: http://www.xuelu.org
feed: /atom.xml

#静态资源配置
static:
  default: http://www.xuelu.org
  production: http://www.xuelu.org
  development: http://127.0.0.1:4000

#菜单配置
nav:
  - text: 首页
    url: /index.html
    icon: icon-home
    class: home
  - text: 文章归档
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: 关于我
    url: /about.html
    icon: icon-heart
    class: none

page:
  - text: 标签
    url: /tags.html
    last: true
  - text: 存档
    url: /archives.html
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /about.html
    last: false

author:
  name: Alfred

JB:
  comments:
    provider: disqus
    disqus:
      short_name: onthedesk
  analytics:
    provider: google
    google:
      tracking_id: UA-16168356-1
